# Generated by Django 5.2.11 on 2026-04-24 05:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='movie_title_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
